// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('/../../../../../../../lib/sources/base.js', ['zz.net'], ['zz.net.WebSocketServer'], false);
goog.addDependency('/../../../../../../../lib/sources/enums/errortype.js', ['zz.net.enums.ErrorType'], [], false);
goog.addDependency('/../../../../../../../lib/sources/websocketserver.js', ['zz.net.WebSocketServer'], ['goog.events.EventTarget', 'zz.environment.services.Environment', 'zz.net.enums.ErrorType'], false);
goog.addDependency('/../../../../../../../node_modules/zz.environment/lib/sources/base.js', ['zz.environment'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.environment/lib/sources/enums/eventtype.js', ['zz.environment.enums.EventType'], ['goog.events'], false);
goog.addDependency('/../../../../../../../node_modules/zz.environment/lib/sources/events/offline.js', ['zz.environments.events.Offline'], ['zz.environment.enums.EventType', 'zz.events.BaseEvent'], false);
goog.addDependency('/../../../../../../../node_modules/zz.environment/lib/sources/events/online.js', ['zz.environment.events.Online'], ['zz.environment.enums.EventType', 'zz.events.BaseEvent'], false);
goog.addDependency('/../../../../../../../node_modules/zz.environment/lib/sources/events/resize.js', ['zz.environment.events.Resize'], ['zz.environment.enums.EventType', 'zz.events.BaseEvent'], false);
goog.addDependency('/../../../../../../../node_modules/zz.environment/lib/sources/services/environment.js', ['zz.environment.services.Environment'], ['goog.dom.ViewportSizeMonitor', 'goog.events', 'goog.events.EventTarget', 'goog.labs.userAgent.browser', 'goog.labs.userAgent.device', 'goog.labs.userAgent.engine', 'goog.labs.userAgent.platform', 'zz.environment.events.Resize', 'zz.services.BaseService'], false);
goog.addDependency('/../../../../../../../node_modules/zz.environment/node_modules/zz.events/lib/sources/base.js', ['zz.events'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.environment/node_modules/zz.events/lib/sources/events/baseevents.js', ['zz.events.BaseEvent'], ['goog.events.Event'], false);
goog.addDependency('/../../../../../../../node_modules/zz.environment/node_modules/zz.services/lib/sources/base.js', ['zz.services'], [], false);
goog.addDependency('/../../../../../../../node_modules/zz.environment/node_modules/zz.services/lib/sources/services/baseservice.js', ['zz.services.BaseService'], ['goog.events', 'goog.events.EventTarget'], false);
